# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      run: mvn clean test -s settings.xml
    - name: The job has failed
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: github_automatically_test
        SLACK_ICON_EMOJI: ':thinking_face:'
        SLACK_MESSAGE: 'Maven test failed'
        SLACK_TITLE: itm-spo-sdk-java
        SLACK_USERNAME: github_mvn_test
    - name: The job is success
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: github_automatically_test
        SLACK_ICON_EMOJI: ':sunglasses:'
        SLACK_MESSAGE: 'Maven test success'
        SLACK_TITLE: itm-spo-sdk-java
        SLACK_USERNAME: github_mvn_test
